<?php
/**
 * $this->renderCategoriesMenuHtml() supports optional arguments:
 * int Level number for list item class to start from
 * string Extra class of outermost list items
 * string If specified wraps children list in div with this class
 */
?>
<?php $_menu = $this->renderCategoriesMenuHtml(0,'level-top') ?>
<div class="nav-container">
    <ul id="">
        <li><a href="<?php echo $this->getBaseUrl(); ?>"><img src="<?php echo $this->getSkinUrl('images/nav_home.gif'); ?>" /></a></li>
        <li><a href="<?php echo $this->getUrl('how-it-work'); ?>"><img src="<?php echo $this->getSkinUrl('images/nav_howitworks.jpg'); ?>" /></a></li>
        <li><a href="<?php echo $this->getUrl('success-stories'); ?>"><img src="<?php echo $this->getSkinUrl('images/nav_successstory.jpg'); ?>" /></a></li>
        <li><a href="<?php echo $this->getUrl('suggested-use'); ?>"><img src="<?php echo $this->getSkinUrl('images/nav_suggesteduse.jpg'); ?>" /></a></li>
        <li><a href="<?php echo $this->getUrl('tea-benefits'); ?>"><img src="<?php echo $this->getSkinUrl('images/nav_teabenefits.jpg'); ?>" /></a></li>
        <li><a href="<?php echo $this->getUrl('shop.html'); ?>"><img src="<?php echo $this->getSkinUrl('images/nav_shop.jpg'); ?>" /></a></li>
        <li><a href="<?php echo $this->getUrl("pallas-story"); ?>"><img src="<?php echo $this->getSkinUrl('images/nav_about.gif'); ?>" /></a></li>
        <?php //if($_menu): ?>
            <?php //echo $_menu ?>
        <?php //endif ?>
        <?php $additionalLink = themeOptions('additionalLink'); ?>
        <?php $additionalLinkUrl = themeOptions('additionalLinkUrl'); ?>
    </ul>
</div>