<?php
/**
 * $this->renderCategoriesMenuHtml() supports optional arguments:
 * int Level number for list item class to start from
 * string Extra class of outermost list items
 * string If specified wraps children list in div with this class
 */
?>
<?php $_menu = $this->renderCategoriesMenuHtml(0,'level-top') ?>
<div class="nav-container">
    <ul id="nav">
        <li class="level0 first homelink"><a href="<?php echo $this->getBaseUrl(); ?>"><span><?php echo $this->__('Home') ?></span></a></li>
        <li class="level0 first homelink"><a href="<?php echo $this->getUrl('how-it-work'); ?>"><span><?php echo $this->__('How it work') ?></span></a></li>
        <li class="level0 first homelink"><a href="<?php echo $this->getUrl('certified'); ?>"><span><?php echo $this->__('Certified') ?></span></a></li>
        <li class="level0 first homelink"><a href="<?php echo $this->getUrl('success-story'); ?>"><span><?php echo $this->__('Success story') ?></span></a></li>
        <li class="level0 first homelink"><a href="<?php echo $this->getUrl('press-release'); ?>"><span><?php echo $this->__('Press release') ?></span></a></li>
        <li class="level0 first homelink"><a href="<?php echo $this->getUrl('how-to-use'); ?>"><span><?php echo $this->__('How to use') ?></span></a></li>
        <li class="level0 first homelink"><a href="<?php echo $this->getUrl("weightcate.html"); ?>"><span><?php echo $this->__('Shop') ?></span></a></li>
        <?php //if($_menu): ?>
            <?php //echo $_menu ?>
        <?php //endif ?>
        <?php $additionalLink = themeOptions('additionalLink'); ?>
        <?php $additionalLinkUrl = themeOptions('additionalLinkUrl'); ?>
    </ul>
</div>