

<?php if($this->isActiveLike()):?>
<?php $product = Mage::registry('current_product'); ?>
    
<meta property="fb:app_id" content="<?php echo $this->getAppId()?>"/>
<?php if ($product): ?>
<meta property="og:title" content="<?php echo htmlspecialchars(trim($product->getName())); ?>"/>
<meta property="og:image" content="<?php echo $this->helper('catalog/image')->init($product, 'thumbnail')?>"/>
<?php endif; ?>
<meta property="og:url" content="<?php echo $this->helper('core/url')->getCurrentUrl();?>"/>
<meta property="og:type" content="product"/>
<?php endif?>