<?php
/**
 * @name         :  Apptha FB Referral
 * @version      :  1.2
 * @since        :  Magento 1.5
 * @author       :  Apptha - http://www.apptha.com
 * @copyright    :  Copyright (C) 2011 Powered by Apptha
 * @license      :  http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 * @Creation Date:  December 01 2011
 *
 * */
$cartItems = Mage::helper('checkout/cart')->getCart()->getItemsCount();

$facebook = $this->getFacebook();
$fbuser = $facebook->getUser();

$content = '<div style=" margin-bottom:15px;width:100%; height:40px; text-align:right;">&nbsp;';
if($fbuser){
	$content .= '<a href="' . $this->getResponseUrl() . '"><img src="'. $this->getSkinUrl("images/fb-recommend.png").'"></a>';
}else{
	$content .= '<a href="' . $this->getFacebookLoginUrl() . '"><img src="'. $this->getSkinUrl("images/fb-recommend.png").'"></a>';
}
$content .= '</div>';

echo $content;
?>
