<?php
/**
 * @see Mage_Page_Block_Template_Links
 */
?>


<?php $_links = $this->getLinks(); ?>

<?php if(!Mage::getSingleton('customer/session')->isLoggedIn()):?>
	<div id="fb-root"></div>
	<div><img src="<?php echo $this->getSkinUrl('images/sharesuit/login_with.jpg');?>">
	<?php if(Mage::getModel('sharesuit/sharesuit')->getFbLogin()):?>
		<script language="JavaScript" type="text/javascript">
	/*<![CDATA[*/
	window.fbAsyncInit = function() {
		FB.init({appId: '<?php echo Mage::getModel('sharesuit/sharesuit')->getFbAppid();?>',             
		    	status     : true, 
	            cookie     : true,
	            xfbml      : true,
	            oauth      : true});
	
		FB.getLoginStatus(function(response) {
		   if (response.status == 'connected') {
		    <?php if (Mage::getSingleton('customer/session')->isLoggedIn() && $uid = Mage::helper('sharesuit')->checkFbuserstatus()):?>
		      greet('<?php echo $uid?>');
		    <?php endif?>
		   }
		});
	};
	(function(d){
	           var js, id = 'facebook-jssdk'; if (d.getElementById(id)) {return;}
	           js = d.createElement('script'); js.id = id; js.async = true;
	           js.src = "//connect.facebook.net/<?php echo Mage::app()->getLocale()->getLocaleCode()?>/all.js";
	           d.getElementsByTagName('head')[0].appendChild(js);
	         }(document));
	
	function login(){
		   document.location.href="<?php echo $this->getUrl('sharesuit/customer/fblogin')?>?referer=<?php echo Mage::helper('core')->urlEncode($this->helper('core/url')->getCurrentUrl())?>";
		}
		function logout(){
		   document.location.href="<?php echo $this->getUrl('sharesuit/customer/fblogout')?>";
		}
		function greet(id){
		   FB.api('/me', function(response) {
			var src = 'https://graph.facebook.com/'+id+'/picture';
			$$('.welcome-msg')[0].insert('<img height="20" src="'+src+'"/>');
		   });
		}
	
	    function fblogin(){
	        FB.login(function(response) {
	
	           if (response.status == 'connected') {
	                login();
	            } else {
	                // user is not logged in
	                window.location.reload();
	            }
	        }, {scope:'email,publish_stream'});
	        return false;
	    }
	/*]]>*/
	</script><a href="#" onclick="return fblogin();" class="fb_button_ps"><img src="<?php echo $this->getSkinUrl('images/sharesuit/login_facebook.jpg');?>" alt="<?php echo $this->__('Login with Facebook')?>" /></a>
	<?php endif?>
	<?php if(Mage::getModel('sharesuit/sharesuit')->getTwLogin()):?>
		
		<a href="<?php echo Mage::helper('sharesuit')->getTwLoginurl();?>" class="fb_button_ps"><img src="<?php echo $this->getSkinUrl('images/sharesuit/login_twitter.jpg');?>" alt="<?php echo $this->__('Login with Twitter')?>" /></a>
	<?php endif?>
	<?php if(Mage::getModel('sharesuit/sharesuit')->getGpLogin()):?>
	
		<a href="#" class="fb_button_ps"><img src="<?php echo $this->getSkinUrl('images/sharesuit/login_googleplus.jpg');?>" alt="<?php echo $this->__('Login with Twitter')?>" /></a>
	<?php endif?>
</div>
<?php endif?>

<?php if(count($_links)>0): ?>
<ul class="links"<?php if($this->getName()): ?> id="<?php echo $this->getName() ?>"<?php endif;?>>
    <?php foreach($_links as $_link): ?>
        <?php if ($_link instanceof Mage_Core_Block_Abstract):?>
            <?php echo $_link->toHtml() ?>
        <?php else: ?>
            <li<?php if($_link->getIsFirst()||$_link->getIsLast()): ?> class="<?php if($_link->getIsFirst()): ?>first<?php endif; ?><?php if($_link->getIsLast()): ?> last<?php endif; ?>"<?php endif; ?> <?php echo $_link->getLiParams() ?>><?php echo $_link->getBeforeText() ?><a href="<?php echo $_link->getUrl() ?>" title="<?php echo $_link->getTitle() ?>" <?php echo $_link->getAParams() ?>><?php echo $_link->getLabel() ?></a><?php echo $_link->getAfterText() ?></li>
        <?php endif;?>
    <?php endforeach; ?>
</ul>
<?php endif; ?>
