<?php if($this->getItems()->getSize()): ?>    
<div class="block-related">
    <h5>You may also be interested in the following product(s)</h5>
    <p class="related-block-subtitle"><?php echo $this->__('Check items to add to the cart or') ?>&nbsp;<a href="#" onclick="selectAllRelated(this); return false;"><?php echo $this->__('select all') ?></a></p>
    <div class="clear"></div>
    <div id="mycarousel" class="touchcarousel grey-blue related-slider">
        <ol class="related touchcarousel-container" >        
        <?php $_i_related = -1; ?>
        <?php foreach($this->getItems() as $_item): $_i_related++; ?>
            <li class="item touchcarousel-item">
                <div class="product">
                <?php if(!$_item->isComposite() && $_item->isSaleable()): ?>
                    <?php if (!$_item->getRequiredOptions()): ?>
                        <input type="checkbox" class="checkbox related-checkbox" id="related-checkbox<?php echo $_item->getId() ?>" name="related_products[]" value="<?php echo $_item->getId() ?>" />
                    <?php endif; ?>
                <?php endif; ?>
                    <a href="<?php echo $_item->getProductUrl() ?>" title="<?php echo $this->htmlEscape($_item->getName()) ?>" class="product-image"><img src="<?php echo $this->helper('catalog/image')->init($_item, 'thumbnail')->resize(228) ?>" width="228" height="228" alt="<?php echo $this->htmlEscape($_item->getName()) ?>" /></a>
                    <div class="product-details">
                        <p class="product-name"><a href="<?php echo $_item->getProductUrl() ?>"><?php echo $this->htmlEscape($_item->getName()) ?></a></p>
                        <?php echo $this->getPriceHtml($_item, true, '-related') ?>
                        <?php if ($this->helper('wishlist')->isAllow()) : ?>
                            <!--a href="<?php echo $this->getAddToWishlistUrl($_item) ?>" class="link-wishlist"><?php echo $this->__('Add to Wishlist') ?></a-->
                        <?php endif; ?>
                    </div>
                </div>
            </li>
        <?php endforeach ?>
        </ol>
        <script type="text/javascript">decorateList('mini-products-list', 'none-recursive')</script>
        <div class="clear"></div>
    </div>
    <?php if($this->getItems()->getSize() > 4): ?>
        <script type="text/javascript">
			jQuery("#mycarousel").touchCarousel({					
				pagingNav: false,
				snapToItems: false,
				itemsPerMove: 1,				
				scrollToLast: false,
				loopItems: false,
				scrollbar: false
		    });	  
        </script>   
    <?php endif; ?>    
    <script type="text/javascript">
    //<![CDATA[
    $$('.related-checkbox').each(function(elem){
        Event.observe(elem, 'click', addRelatedToProduct)
    });

    var relatedProductsCheckFlag = false;
    function selectAllRelated(txt){
        if (relatedProductsCheckFlag == false) {
            $$('.related-checkbox').each(function(elem){
                elem.checked = true;
            });
            relatedProductsCheckFlag = true;
            txt.innerHTML="<?php echo $this->__('unselect all') ?>";
        } else {
            $$('.related-checkbox').each(function(elem){
                elem.checked = false;
            });
            relatedProductsCheckFlag = false;
            txt.innerHTML="<?php echo $this->__('select all') ?>";
        }
        addRelatedToProduct();
    }

    function addRelatedToProduct(){
        var checkboxes = $$('.related-checkbox');
        var values = [];
        for(var i=0;i<checkboxes.length;i++){
            if(checkboxes[i].checked) values.push(checkboxes[i].value);
        }
        if($('related-products-field')){
            $('related-products-field').value = values.join(',');
        }
    }
    //]]>
    </script>
</div>
<?php endif ?>
