<?php if (($_products = $this->getProductCollection()) && $_products->getSize()): ?>
<?php $now = date("Y-m-d H:m:s"); ?>
    <div id="mycarousel" class="touchcarousel grey-blue">
        <ul class="newproducts touchcarousel-container">
            <?php $i=0; foreach ($_products->getItems() as $_product): $i++; ?>
                <li class="item touchcarousel-item <?php if($i == 4 && $_products->getSize() < 5) echo 'last'?>">
                    <?php $newFromDate = $_product->getNewsFromDate(); ?>
                    <?php $newToDate = $_product->getNewsToDate(); ?>                                               
                    <?php if($newFromDate < $now && $newToDate > $now): ?>
                            <div class="newproduct_grid"></div>
                    <?php endif; ?>   
                    <?php echo $this->getReviewsSummaryHtml($_product, 'short') ?>          
                    <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->htmlEscape($_product->getName()) ?>" class="product-image"><img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(210) ?>" width="210" height="210" alt="<?php echo $this->htmlEscape($_product->getName()) ?>" /></a>
                    <div class="new-description">
                        <h3><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->htmlEscape($_product->getName()) ?>"><?php echo $this->htmlEscape($_product->getName()) ?></a></h3>
                        <?php echo $this->getPriceHtml($_product, true) ?>                    
                    
                        <?php if($_product->isSaleable()): ?>
								<button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart" onclick="showOptions('<?php echo $_product->getId()?>')"><span><span><?php echo $this->__('Add to Cart') ?></span></span></button>
                                <a href='<?php echo $this->getUrl('ajax/index/options',array('product_id'=>$_product->getId()));?>' class='fancybox' id='fancybox<?php echo $_product->getId()?>' style="display: none;" ><?php echo $this->__('Add to Cart') ?></a>                        <?php else: ?>
                            <p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
                            
                        <?php endif; ?>
                        <div style="clear: both;"></div>
                    </div>                    
                </li>
            <?php endforeach; ?>
        </ul>
    </div>
    <div style="clear: both;"></div>
    <?php if($_products->getSize() > 4): ?>
        <script type="text/javascript">
			jQuery("#mycarousel").touchCarousel({					
				pagingNav: false,
				snapToItems: false,
				itemsPerMove: 1,				
				scrollToLast: false,
				loopItems: false,
				scrollbar: false
		    });	  
        </script>   
    <?php endif; ?>
<?php endif; ?>
<script type="text/javascript" src="<?php echo $this->getSkinUrl();?>js/fancybox/jquery.fancybox-1.3.4.js"></script>
<script type="text/javascript" src="<?php echo $this->getSkinUrl();?>js/fancybox/jquery.easing-1.3.pack.js"></script>
<script type="text/javascript" src="<?php echo $this->getSkinUrl();?>js/fancybox/jquery.mousewheel-3.0.4.pack.js"></script>
<script type="text/javascript" src="<?php echo $this->getSkinUrl();?>js/fancybox/init.js"></script>
<script type="text/javascript">
        jQuery.noConflict();
        jQuery('.fancybox').fancybox({
            hideOnContentClick : true,
            width: 582,
            autoDimensions: true,
            type : 'iframe',
            showTitle: false,
            scrolling: 'no',
            onComplete: function(){ //Resize the iframe to correct size
            jQuery('#fancybox-frame').load(function() { // wait for frame to load and then gets it's height
                jQuery('#fancybox-content').height(jQuery(this).contents().find('body').height()+30);
                jQuery.fancybox.resize();
             });
            
            }
        });
        function showOptions(id){
            jQuery('#fancybox'+id).trigger('click');
        }
        function setAjaxData(data,iframe){
            if(data.status == 'ERROR'){
                alert(data.message);
            }else{
                if(jQuery('.block-cart')){
                    jQuery('.block-cart').replaceWith(data.sidebar);
                }
                if(jQuery('.header .block-cart-header')){
                    jQuery('.header .block-cart-header').replaceWith(data.topcart);
                } 
                jQuery.fancybox.close();
            }
        }
        function setLocationAjax(url,id){
            url += 'isAjax/1';
            url = url.replace("checkout/cart","ajax/index");
            var msgHtml;
            var productImg = jQuery('#productimgover' + id).html();
            var windowOver = jQuery('#addedoverlay');
            var windowBox = jQuery('#added');
            var titleForBox = jQuery('#productname' + id).text();
            windowOver.show();
			windowBox.show().css({
                backgroundImage: "url('<?php echo $this->getSkinUrl('images/loading.gif')?>')"
			});
            try {
                jQuery.ajax( {
                    url : url,
                    dataType : 'json',
                    success : function(data) {
                        if(data.status == 'SUCCESS'){    
                            msgHtml = '<div style="float:left;">' + productImg + '</div><em>' + titleForBox + '</em> <?php echo $this->__('was successfully added to your shopping cart.') ?><div style="clear:both;"></div><a id="hidewindow" href="javascript:void(0);"><?php echo $this->__('Continue shopping') ?></a>&nbsp;<a href="<?php echo $this->getUrl('checkout/cart')?>"><?php echo $this->__('View cart & checkout') ?></a>';             
                        }else{
                            msgHtml = '<p class="error-msg" style="margin-bottom:15px;">' + data.message + '</p><a id="hidewindow" href="javascript:void(0);"><?php echo $this->__('Continue shopping') ?></a>&nbsp;<a href="<?php echo $this->getUrl('checkout/cart')?>"><?php echo $this->__('View cart & checkout') ?></a>';
                        }            
                        setAjaxData(data,false);
                        
  			            windowBox.css({
               			      backgroundImage: 'none'
	                    }).html(msgHtml);					   
                        windowOver.one('click',function(){
				            hidewindow(windowBox,windowOver);                    
                        });	       
                                         
                        jQuery('#hidewindow').click(function(){
				            hidewindow(windowBox,windowOver);                    
                        });                        
                    }
                });
            } catch (e) {
            }
        }
        function hidewindow(windowBox,windowOver){
            windowOver.fadeOut(400);
            windowBox.fadeOut(400).html('');	
        }        
        </script>