<?php $_productCollection=$this->getLoadedProductCollection() ?>
<?php $_helper = $this->helper('catalog/output');?>
<?php if(!$_productCollection->count()): ?>

<p class="note-msg"><?php echo $this->__('There are no products matching the selection.') ?></p>
<?php else: ?>

<div class="ahome-products">
<div class="success_title">
	<div class="success_title_img"><img src="<?php echo Mage::getBaseUrl('media'); ?>wysiwyg/weight/success_stories_meet.gif" /></div>
	These real PALLAS ® users drink weight-loss tea to weight loss success. When you read their weight loss stories, you'll be amazed to discover that they reached their goals without traditional dieting - no pills, no stimulants and no counting calories. Just look at these transformations! They're proof that weight loss success can be achieved simply and healthily. If you would like to share your success story, just contact us, we will send you great gifts for your sharing. 
</div>
<script type="text/javascript" src="<?php echo $this->getSkinUrl();?>js/artDialog.js"></script>
<script type="text/javascript" src="<?php echo $this->getSkinUrl();?>js/jquery.artDialog.js"></script>
<?php $_collectionSize = $_productCollection->count() ?>
<input type="hidden" id="idcount" value="<?php echo $_collectionSize;?>">
    <?php $_columnCount = 3; ?>
    <?php $i=0;$ids=1; foreach ($_productCollection as $_product): ?>
   	 <input type="hidden" name="ids" value="<?php echo $_product->getId();?>">
        <?php if ($i++%$_columnCount==0): ?>
        <ul class="products-grid">
        <?php endif ?>
            <li class="item<?php if(($i-1)%$_columnCount==0): ?> first<?php elseif($i%$_columnCount==0): ?> last<?php endif; ?>">
                <a href="#<?php echo $_product->getSku();?>" onclick="dial(<?php echo $_product->getId().",".$ids ?>);" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image"><img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(290, 400); ?>" width="260" height="320" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" /></a>
                <div class="moreinfo">
                    <h2 class="product-name"><a href="javascript:void(0)" style="color:#6291F1;" onclick="dial(<?php echo $_product->getId().",".$ids ?>);" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>"><?php echo $this->htmlEscape($_product->getName()) ?></a></h2>
                    <div id='productname<?php echo $_product->getId()?>' style='display:none'><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></div>
                    <?php $productss = Mage::getModel('catalog/product')->load($_product->getId());//echo $this->getPriceHtml($_product, true) ?>
                    <div style="display: none;" id="productimg<?php echo $_product->getId()?>"><img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(350, 530); ?>" width="360" height="500" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" /></div>
                    <div style="display: none;" id="productdetail<?php echo $_product->getId();?>"><?php echo $productss->getDescription();?></div>
                    <div class="clear"></div>
                </div>
            </li>
        <?php if ($i%$_columnCount==0 || $i==$_collectionSize): ?>
        </ul>
        <?php endif ?>
        <?php $ids++;endforeach ?>
</div>
<div id="dial" style="display:none;">
</div>
<script type="text/javascript">
function dial(id,ids){
	var name = document.getElementById('productname'+id).innerHTML;
	var img = document.getElementById('productimg'+id).innerHTML;
	var detail = document.getElementById('productdetail'+id).innerHTML;
	//alert(document.getElementsByName('ids')[ids-1].value+'**'+document.getElementById('idcount').value);
	if(ids > 1){
		ids = ids -1;
     } else {
		ids = document.getElementById('idcount').value;
	}
	id = document.getElementsByName('ids')[ids-1].value;
	var dialog = art.dialog({
		//title: val,
		//width:650,
		height:500,
		content: '<div class="dialogs" id="dialogs"><div style="float:left; width:370px;">'+img+'</div><div style="float:right; width:230px; max-height:500px;overflow:auto;"><font style="font-size:14px;"><b>'+name+'</b></font><br>'+detail+'</div></div>',
		drag: false,
		lock: true,
		button: [
		         {
		             name: 'prev',
		             callback: function () {
			             
		            	 dial(id,ids);
		            	 this.close();
		             },
		             focus: true,
		             className:'left'
		         },
		         {
		             name: 'next',
		             callback: function () {
		            	 dial(id,ids);
		            	 this.close();
		             }
		         },
		     ]
	});
}
</script>
<?php endif; ?>


<script type="text/javascript" src="<?php echo $this->getSkinUrl();?>js/fancybox/jquery.fancybox-1.3.4.js"></script>
<script type="text/javascript" src="<?php echo $this->getSkinUrl();?>js/fancybox/jquery.easing-1.3.pack.js"></script>
<script type="text/javascript" src="<?php echo $this->getSkinUrl();?>js/fancybox/jquery.mousewheel-3.0.4.pack.js"></script>
<script type="text/javascript" src="<?php echo $this->getSkinUrl();?>js/fancybox/init.js"></script>
<script type="text/javascript">
        jQuery.noConflict();
        jQuery('.fancybox').fancybox({
            hideOnContentClick : true,
            width: 582,
            autoDimensions: true,
            type : 'iframe',
            showTitle: false,
            scrolling: 'no',
            onComplete: function(){ //Resize the iframe to correct size
            jQuery('#fancybox-frame').load(function() { // wait for frame to load and then gets it's height
                jQuery('#fancybox-content').height(jQuery(this).contents().find('body').height()+30);
                jQuery.fancybox.resize();
             });
            
            }
        });
        function showOptions(id){
            jQuery('#fancybox'+id).trigger('click');
        }
        function setAjaxData(data,iframe){
            if(data.status == 'ERROR'){
                alert(data.message);
            }else{
                if(jQuery('.block-cart')){
                    jQuery('.block-cart').replaceWith(data.sidebar);
                }
                if(jQuery('.header .block-cart-header')){
                    jQuery('.header .block-cart-header').replaceWith(data.topcart);
                } 
                jQuery.fancybox.close();
            }
        }
        function setLocationAjax(url,id){
            url += 'isAjax/1';
            url = url.replace("checkout/cart","ajax/index");
            var msgHtml;
            var productImg = jQuery('#productimgover' + id).html();
            var windowOver = jQuery('#addedoverlay');
            var windowBox = jQuery('#added');
            var titleForBox = jQuery('#productname' + id).text();
            windowOver.show();
			windowBox.show().css({
                backgroundImage: "url('<?php echo $this->getSkinUrl('images/loading.gif')?>')"
			});
            try {
                jQuery.ajax( {
                    url : url,
                    dataType : 'json',
                    success : function(data) {
                        if(data.status == 'SUCCESS'){    
                            msgHtml = '<div style="float:left;">' + productImg + '</div><em>' + titleForBox + '</em> <?php echo $this->__('was successfully added to your shopping cart.') ?><div style="clear:both;"></div><a id="hidewindow" href="javascript:void(0);"><?php echo $this->__('Continue shopping') ?></a>&nbsp;<a href="<?php echo $this->getUrl('checkout/cart')?>"><?php echo $this->__('View cart & checkout') ?></a>';             
                        }else{
                            msgHtml = '<p class="error-msg" style="margin-bottom:15px;">' + data.message + '</p><a id="hidewindow" href="javascript:void(0);"><?php echo $this->__('Continue shopping') ?></a>&nbsp;<a href="<?php echo $this->getUrl('checkout/cart')?>"><?php echo $this->__('View cart & checkout') ?></a>';
                        }            
                        setAjaxData(data,false);
                        
  			            windowBox.css({
               			      backgroundImage: 'none'
	                    }).html(msgHtml);					   
                        windowOver.one('click',function(){
				            hidewindow(windowBox,windowOver);                    
                        });	       
                                         
                        jQuery('#hidewindow').click(function(){
				            hidewindow(windowBox,windowOver);                    
                        });                        
                    }
                });
            } catch (e) {
            }
        }
        function hidewindow(windowBox,windowOver){
            windowOver.fadeOut(400);
            windowBox.fadeOut(400).html('');	
        }        
        </script>