<div class="fban">
	<div id="slider">
	    <div class="coin-slider" id="coin-slider-coin-slider">
	    <div id="coin-slider" style="width: 660px; height: 320px; position: relative; background-position: 0% 0%; ">
	        <a href="#"><img src="<?php echo $this->getSkinUrl('images/banner-shoes1.jpg')?>" alt="" class="clsbannerimg" /></a>
	        <a href="#"><img src="<?php echo $this->getSkinUrl('images/banner-shoes2.jpg')?>" alt="" class="clsbannerimg" /></a>
	    </div>
	    <SCRIPT>jqs(document).ready(function() { jqs('#coin-slider').coinslider();});</SCRIPT>
		</div>
	</div>
	<div class="rbanner">
		<img src="<?php echo $this->getSkinUrl('images/r-banner.jpg')?>">
	</div>
</div>
