<?php
/**
 * $this->renderCategoriesMenuHtml() supports optional arguments:
 * int Level number for list item class to start from
 * string Extra class of outermost list items
 * string If specified wraps children list in div with this class
 */
?>
<?php $_menu = $this->renderCategoriesMenuHtml(0,'level-top') ?>
<div class="nav-container">
    <ul id="nav">
        <li class="level0 first homelink"><a href="<?php echo $this->getBaseUrl(); ?>"><span><?php echo $this->__('Home') ?></span></a></li>
        <?php if($_menu): ?>
            <?php echo $_menu ?>
        <?php endif ?>
        <?php $additionalLink = themeOptions('additionalLink'); ?>
        <?php $additionalLinkUrl = themeOptions('additionalLinkUrl'); ?>
        <?php if($additionalLinkUrl && $additionalLink): ?>
            <li class="level0 clearence"><a href="<?php echo $additionalLinkUrl ?>" title="<?php echo $additionalLink ?>"><span><?php echo $additionalLink ?></span></a></li>
        <?php endif ?>        
    </ul>
</div>