<?php $_productCollection=$this->getLoadedProductCollection() ?>
<?php if(!$_productCollection->count()): ?>
<p class="note-msg"><?php echo $this->__('There are no products matching the selection.') ?></p>
<?php else: ?>

<script type="text/javascript" src="<?php echo $this->getSkinUrl();?>js/lib.min.js"></script>
<script type="text/javascript" src="<?php echo $this->getSkinUrl();?>js/jquery.jcarousellite.min.js"></script>
<script type="text/javascript" src="<?php echo $this->getSkinUrl();?>js/script_jcarousellite.js"></script>
<div class="flash">
    <div id="jCarouselLiteDemo" class="cEnd">
		<div class="carousel main">
			<img src="<?php echo $this->getSkinUrl();?>images/iconleft.gif">
			    <div class="jCarouselLite">
			        <ul>

				    <?php $_collectionSize = $_productCollection->count() ?>
				    <?php $_columnCount = $this->getColumnCount(); ?>
				    <?php $i=0; foreach ($_productCollection as $_product): ?>
						<li>
					        <a class="product-image" href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->htmlEscape($this->getImageLabel($_product, 'small_image')) ?>" target="_blank"><img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(208,208); ?>" width="208" height="208" alt="<?php echo $this->htmlEscape($this->getImageLabel($_product, 'small_image')) ?>" /></a>
					        <h3 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->htmlEscape($_product->getName()) ?>" target="_blank"><?php echo $this->htmlEscape($_product->getName()) ?></a>
					    </li>
		        	<?php endforeach ?>
				</ul>
            	</div>
            <img src="<?php echo $this->getSkinUrl();?>images/iconright.gif">
        <div class="clear"></div>   
    </div>        
</div>
<?php endif; ?>



