<?php
    $_product = $this->getProduct();
    $_helper = $this->helper('catalog/output');
    $now = date("Y-m-d H:m:s");     
    $use_zoom = themeOptions('use_zoom'); 
    $use_carousel = themeOptions('use_carousel'); 
    $thumbs_count = count($this->getGalleryImages());
    $_i_thumbs = 0;
?>

    
<div class="zoom-container">
    <div class="main-image" >   
        <a id="zoom" class="<?php if(!$use_zoom): ?> lightbox<?php endif;?> main-thumbnail" href="<?php echo $this->helper('catalog/image')->init($_product, 'image') ?>">
            <?php
                $_img = '<img class="zoom-image" src="'.$this->helper('catalog/image')->init($_product, 'image')->resize(390).'" width="390" height="390" alt="'.$this->htmlEscape($this->getImageLabel()).'" title="'.$this->htmlEscape($this->getImageLabel()).'" />';
                echo $_helper->productAttribute($_product, $_img, 'image');
            ?>
        </a> 
        <?php if($use_zoom): ?>
        <div class="lightbox-btn">
            <a id="zoom" class="lightbox" href="<?php echo $this->helper('catalog/image')->init($_product, 'image') ?>">
                <?php echo $this->__('Enlarge') ?>
            </a>        
        </div>
        <?php endif;?>
    </div> 
    <div class="clear"></div>
    <script type="text/javascript" src="<?php echo $this->getSkinUrl();?>js/jcarousellite_1.0.1.pack.js"></script>

    <?php $newFromDate = $_product->getNewsFromDate(); ?>
    <?php $newToDate = $_product->getNewsToDate(); ?>                                               
    <?php if($newFromDate < $now && $newToDate > $now): ?>
        <div class="newproduct_grid"><?php echo $this->__('New Product') ?></div>
    <?php endif; ?> 
    
  
</div>    
    
	<script type="text/javascript">
    <?php if ($_product->getImage() != 'no_selection' && $_product->getImage()): ?>        
    	
        <?php if($use_zoom): ?>
            // Start easyZoom
        	jQuery('#zoom')
        		.easyZoom({
        			parent: 'div.zoom-container',
        			preload: '',
                    lightboxBtn: '.lightbox-btn .lightbox'
        		})
        		.data('easyZoom')
        		.gallery('a.zoom-thumbnail');
        <?php endif;?>
    <?php endif; ?> 
    
    
     // Start lightbox
    jQuery('a.lightbox').lightBox({
        imageLoading    : '<?php echo $this->getSkinUrl('images/lightbox-ico-loading.gif') ?>',
        imageBtnClose   : '<?php echo $this->getSkinUrl('images/lightbox-btn-close.gif') ?>',
        imageBtnNext    : '<?php echo $this->getSkinUrl('images/lightbox-btn-next.gif') ?>',
        imageBtnPrev    : '<?php echo $this->getSkinUrl('images/lightbox-btn-prev.gif') ?>',
        imageBlank      : '<?php echo $this->getSkinUrl('images/lightbox-blank.gif') ?>',
        fixedNavigation : true
    });        
	</script>   
