<?php if ($this->getIsNeedToDisplaySideBar()):?>
<div class="block_cart ">
    <?php $_cartQty = $this->getSummaryCount(); ?>
    <div class="summary">
            <table width="100%">
                <tbody><tr>
                    <td>
                         <a href="<?php echo $this->getUrl('checkout/cart')?>"><?php echo $this->__('Shopping Cart')?></a><?php if($_cartQty > 0): ?> (<?php echo $_cartQty ?> <?php echo ($_cartQty == 1) ? $this->__('item') : $this->__('items'); ?>)<?php endif; ?>
			        - <?php if ($this->canApplyMsrp()): ?>
			            <span class="map-cart-sidebar-total"><?php echo $this->__('ORDER TOTAL WILL BE DISPLAYED BEFORE YOU SUBMIT THE ORDER'); ?></span>
			        <?php else: ?>
			            <?php echo Mage::helper('checkout')->formatPrice($this->getSubtotal()) ?>
			            <?php if ($_subtotalInclTax = $this->getSubtotalInclTax()): ?>
			                <?php echo Mage::helper('checkout')->formatPrice($_subtotalInclTax) ?> <?php echo Mage::helper('tax')->getIncExcText(true) ?>
			            <?php endif; ?>
			        <?php endif; ?>                                              
                    </td>
                    
                </tr>
            </tbody></table>
        </div>


    <?php if($_cartQty && $this->isPossibleOnepageCheckout()): ?>
    <div class="actions">
        <?php echo $this->getChildHtml('extra_actions') ?>
        <button type="button" title="<?php echo $this->__('Checkout') ?>" class="button" onclick="setLocation('<?php echo $this->getCheckoutUrl() ?>')"><span><span><?php echo $this->__('Checkout') ?></span></span></button>
    </div>
    <?php endif ?>
</div>
<?php endif;?>
