<?php
    $_product = $this->getProduct();
    $_helper = $this->helper('catalog/output');
    $now = date("Y-m-d H:m:s");     
    $use_zoom = themeOptions('use_zoom'); 
    $use_carousel = themeOptions('use_carousel'); 
    $thumbs_count = count($this->getGalleryImages());
    $_i_thumbs = 0;
?>

    
<div class="zoom-container">
    <div class="main-image" >   
        <a id="zoom" class="<?php if(!$use_zoom): ?> lightbox<?php endif;?> main-thumbnail" href="<?php echo $this->helper('catalog/image')->init($_product, 'image') ?>">
            <?php
                $_img = '<img class="zoom-image" src="'.$this->helper('catalog/image')->init($_product, 'image')->resize(390).'" width="390" height="390" alt="'.$this->htmlEscape($this->getImageLabel()).'" title="'.$this->htmlEscape($this->getImageLabel()).'" />';
                echo $_helper->productAttribute($_product, $_img, 'image');
            ?>
        </a> 
        <?php if($use_zoom): ?>
        <div class="lightbox-btn">
            <a id="zoom" class="lightbox" href="<?php echo $this->helper('catalog/image')->init($_product, 'image') ?>">
                <?php echo $this->__('Enlarge') ?>
            </a>        
        </div>
        <?php endif;?>
    </div> 
    
    <div class="more-views">
    <script type="text/javascript" src="<?php echo $this->getSkinUrl();?>js/jquery-1.3.2.min.js"></script>
<script type="text/javascript" src="<?php echo $this->getSkinUrl();?>js/slider.js"></script>
<script type="text/javascript">
	jQuery.noConflict();
	jQuery(window).bind('load', function(){
		jQuery().prepare_slider(); 
		jQuery('#slider_list li').over();
				
		if (jQuery('#slider_list').length > 0){
			jQuery('.left-top').css("background","none")
			jQuery('.right-top').css("background","none")
			jQuery('.left-bot').css("background","none")
			jQuery('.right-bot').css("background","none")
		}
		
		jQuery(".box-left").hover(
			  function () {
				jQuery(this).addClass('box-left-hover');
			  }, 
			  function () {
				jQuery(this).removeClass('box-left-hover');
			  }
			);
			
		jQuery(".box-right").hover(
			  function () {
				jQuery(this).addClass('box-right-hover');
			  }, 
			  function () {
				jQuery(this).removeClass('box-right-hover');
			  }
			);

	});	
</script>
        <ul class="zoom-gallery jcarousel-skin-tango" id="slider_list">
        <?php if($thumbs_count == 0): ?>
            <li class="last">
                <a class="zoom-thumbnail<?php if(!$use_zoom): ?> lightbox<?php endif;?>" href="<?php echo $this->helper('catalog/image')->init($_product, 'image') ?>" data-easyzoom-source="<?php echo $this->helper('catalog/image')->init($_product, 'image')->resize(390) ?>">
                    <?php
                        $_img = '<img class="zoom-image" src="'.$this->helper('catalog/image')->init($_product, 'thumbnail')->resize(63).'" width="63" height="63" alt="'.$this->htmlEscape($this->getImageLabel()).'" title="'.$this->htmlEscape($this->getImageLabel()).'" />';
                        echo $_helper->productAttribute($_product, $_img, 'image');
                    ?>
                </a>   
            </li>   
        <?php endif; ?>
        <?php if ($thumbs_count > 0): ?>  
            <?php foreach ($this->getGalleryImages() as $_image): $_i_thumbs++; ?>
                <li class="<?php if($thumbs_count == $_i_thumbs) echo 'last'; ?>">
                    <a class="zoom-thumbnail<?php if(!$use_zoom): ?> lightbox<?php endif;?>"  href="<?php echo $this->helper('catalog/image')->init($this->getProduct(), 'image', $_image->getFile()); ?>" data-easyzoom-source="<?php echo $this->helper('catalog/image')->init($this->getProduct(), 'thumbnail', $_image->getFile())->resize(390); ?>" title="<?php echo $this->htmlEscape($_image->getLabel()) ?>"><img src="<?php echo $this->helper('catalog/image')->init($this->getProduct(), 'thumbnail', $_image->getFile())->resize(63); ?>" width="63" height="63" alt="<?php echo $this->htmlEscape($_image->getLabel()) ?>" /></a>
                </li>
            <?php endforeach; ?>
        <?php endif; ?>
        </ul>
    </div>
    <?php $newFromDate = $_product->getNewsFromDate(); ?>
    <?php $newToDate = $_product->getNewsToDate(); ?>                                               
    <?php if($newFromDate < $now && $newToDate > $now): ?>
        <div class="newproduct_grid"><?php echo $this->__('New Product') ?></div>
    <?php endif; ?> 
    
  
</div>    
    
	<script type="text/javascript">
    <?php if ($_product->getImage() != 'no_selection' && $_product->getImage()): ?>        
    	
        <?php if($use_zoom): ?>
            // Start easyZoom
        	jQuery('#zoom')
        		.easyZoom({
        			parent: 'div.zoom-container',
        			preload: '',
                    lightboxBtn: '.lightbox-btn .lightbox'
        		})
        		.data('easyZoom')
        		.gallery('a.zoom-thumbnail');
        <?php endif;?>
    <?php endif; ?> 
    
    <?php if($use_carousel && $thumbs_count > 5): ?>
    // Start jCarousel
    jQuery('.zoom-gallery').jcarousel({
        scroll: 1,
        vertical:true
    });   
    <?php endif;?>
    
     // Start lightbox
    jQuery('a.lightbox').lightBox({
        imageLoading    : '<?php echo $this->getSkinUrl('images/lightbox-ico-loading.gif') ?>',
        imageBtnClose   : '<?php echo $this->getSkinUrl('images/lightbox-btn-close.gif') ?>',
        imageBtnNext    : '<?php echo $this->getSkinUrl('images/lightbox-btn-next.gif') ?>',
        imageBtnPrev    : '<?php echo $this->getSkinUrl('images/lightbox-btn-prev.gif') ?>',
        imageBlank      : '<?php echo $this->getSkinUrl('images/lightbox-blank.gif') ?>',
        fixedNavigation : true
    });        
	</script>   
