<div id="top"></div>
<div class="header-container">
    <div class="header">
        <div class="header-left">
            <div style="min-height: 35px;">
                <?php echo $this->getChildHtml('store_language') ?>
            </div>            
            <?php if ($this->getIsHomePage()):?>
            <a href="<?php echo $this->getUrl('') ?>" title="<?php echo $this->getLogoAlt() ?>" class="logo"><img src="<?php echo $this->getLogoSrc() ?>" alt="<?php echo $this->getLogoAlt() ?>" /></a>
            <?php else:?>
            <a href="<?php echo $this->getUrl('') ?>" title="<?php echo $this->getLogoAlt() ?>" class="logo"><strong><?php echo $this->getLogoAlt() ?></strong><img src="<?php echo $this->getLogoSrc() ?>" alt="<?php echo $this->getLogoAlt() ?>" /></a>
            <?php endif?>
        </div>
        <div class="header-center">
            <?php if(themeOptions('topbanner') && themeOptions('topbanner') != ''): ?>
                <img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).'wysiwyg/mercado/'.themeOptions('topbanner') ?>" alt="<?php echo $this->getLogoAlt() ?>" />
            <?php endif; ?>
            <?php echo $this->getChildHtml('topBar') ?>   
        </div>        
        <div class="header-right">
            <div class="minicart">
                <?php echo $this->getChildHtml('top_cart') ?>
            </div>  
            <?php echo $this->getChildHtml('currency') ?>  
            <div class="clear"></div> 
            <span class="welcome-msg"><?php echo $this->getWelcome() ?></span>
            <div class="clear"></div>   
            <?php echo $this->getChildHtml('topLinks') ?>  
        </div>      
    </div>
    <?php echo $this->getChildHtml('topMenu') ?>
    <?php echo $this->getChildHtml('topBread') ?>
    <?php echo $this->getChildHtml('topContainer'); ?>

</div>