<meta property="fb:app_id" content="<?php echo Mage::getStoreConfig('facebooklb/general/fb_appid'); ?>"/>
<meta property="og:url" content="<?php echo $this->helper('core/url')->getCurrentUrl();?>"/>
<meta property="og:type" content="product"/>
<?php $product = Mage::registry('current_product');
if ($product): ?>
<meta property="og:title" content="<?php echo trim($product->getName()); ?>"/>
<meta property="og:image" content="<?php echo Mage::helper('catalog/image')->init($product, 'image');?>"/>
<?php endif; ?>
